### ISSUE TITLE
Wrong Powershell

### ISSUE THREAD

**Issue by yang-jiayi** [MicrosoftDocs/MIMDocs.ja-jp#16]
Hey,

New-ADUser –SamAccountName MIMpool –name BackupAdmin
is wrong.

New-ADUser –SamAccountName MIMpool –name MIMpool
is right.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: b63b3e40-9767-a459-3c57-3aad83026b74
* Version Independent ID: d1cf0874-08cc-4c70-44d5-a1a625bdfe42
* Content: [Microsoft Identity Manager 2016 のドメインのセットアップ](https://docs.microsoft.com/ja-jp/microsoft-identity-manager/preparing-domain#feedback)
* Content Source: [MIMDocs/preparing-domain.md](https://github.com/MicrosoftDocs/MIMDocs.ja-jp/blob/live/MIMDocs/preparing-domain.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by srvbpigh** [comment]
Hello, @yang-jiayi
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by yang-jiayi** [comment]
Hey

New-ADUser –SamAccountName MIMINSTALL –name MIMMA
is wrong,too.

New-ADUser -SamAccountName MIMINSTALL -name MIMINSTALL
is right.

**Comment by CeciAc** [comment]
Hello, @yang-jiayi

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/MIMDocs/issues/175

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
